root: true
extends: airbnb-base
plugins:
  - import
env:
  es6: true
  node: true
rules:
  no-param-reassign: 0
  comma-dangle: 0
  arrow-parens: 0
  no-mixed-operators: 0
  no-confusing-arrow: 0
  no-underscore-dangle: 0
